/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AisRouteImport } from './routes/ais'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as ContinentsRouteImport } from './routes/continents'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ProducersRouteImport } from './routes/producers'
import { Route as ReservesRouteImport } from './routes/reserves'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SubstackRouteImport } from './routes/substack'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ContinentsIndexRouteImport } from './routes/continents.index'
import { Route as ContinentsSlugRouteImport } from './routes/continents.$slug'
import { Route as DispatchIndexRouteImport } from './routes/dispatch.index'
import { Route as DispatchSlugRouteImport } from './routes/dispatch.$slug'
import { Route as ProducersIndexRouteImport } from './routes/producers.index'
import { Route as ProducersSlugRouteImport } from './routes/producers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AisRoute = AisRouteImport.update({
  id: '/ais',
  path: '/ais',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinentsRoute = ContinentsRouteImport.update({
  id: '/continents',
  path: '/continents',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducersRoute = ProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservesRoute = ReservesRouteImport.update({
  id: '/reserves',
  path: '/reserves',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstackRoute = SubstackRouteImport.update({
  id: '/substack',
  path: '/substack',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinentsIndexRoute = ContinentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContinentsRoute,
} as any)
const ContinentsSlugRoute = ContinentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ContinentsRoute,
} as any)
const DispatchIndexRoute = DispatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchSlugRoute = DispatchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DispatchRoute,
} as any)
const ProducersIndexRoute = ProducersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProducersRoute,
} as any)
const ProducersSlugRoute = ProducersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProducersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ais': typeof AisRoute
  '/briefing': typeof BriefingRoute
  '/continents': typeof ContinentsRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/flows': typeof FlowsRoute
  '/invest': typeof InvestRoute
  '/jobs': typeof JobsRoute
  '/producers': typeof ProducersRouteWithChildren
  '/reserves': typeof ReservesRoute
  '/signals': typeof SignalsRoute
  '/sources': typeof SourcesRoute
  '/substack': typeof SubstackRoute
  '/trade': typeof TradeRoute
  '/continents/$slug': typeof ContinentsSlugRoute
  '/dispatch/$slug': typeof DispatchSlugRoute
  '/producers/$slug': typeof ProducersSlugRoute
  '/continents/': typeof ContinentsIndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/producers/': typeof ProducersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ais': typeof AisRoute
  '/briefing': typeof BriefingRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/flows': typeof FlowsRoute
  '/invest': typeof InvestRoute
  '/jobs': typeof JobsRoute
  '/reserves': typeof ReservesRoute
  '/signals': typeof SignalsRoute
  '/sources': typeof SourcesRoute
  '/substack': typeof SubstackRoute
  '/trade': typeof TradeRoute
  '/continents/$slug': typeof ContinentsSlugRoute
  '/dispatch/$slug': typeof DispatchSlugRoute
  '/producers/$slug': typeof ProducersSlugRoute
  '/continents': typeof ContinentsIndexRoute
  '/dispatch': typeof DispatchIndexRoute
  '/producers': typeof ProducersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ais': typeof AisRoute
  '/briefing': typeof BriefingRoute
  '/continents': typeof ContinentsRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/flows': typeof FlowsRoute
  '/invest': typeof InvestRoute
  '/jobs': typeof JobsRoute
  '/producers': typeof ProducersRouteWithChildren
  '/reserves': typeof ReservesRoute
  '/signals': typeof SignalsRoute
  '/sources': typeof SourcesRoute
  '/substack': typeof SubstackRoute
  '/trade': typeof TradeRoute
  '/continents/$slug': typeof ContinentsSlugRoute
  '/dispatch/$slug': typeof DispatchSlugRoute
  '/producers/$slug': typeof ProducersSlugRoute
  '/continents/': typeof ContinentsIndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/producers/': typeof ProducersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ais'
    | '/briefing'
    | '/continents'
    | '/dispatch'
    | '/feed.xml'
    | '/flows'
    | '/invest'
    | '/jobs'
    | '/producers'
    | '/reserves'
    | '/signals'
    | '/sources'
    | '/substack'
    | '/trade'
    | '/continents/$slug'
    | '/dispatch/$slug'
    | '/producers/$slug'
    | '/continents/'
    | '/dispatch/'
    | '/producers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ais'
    | '/briefing'
    | '/feed.xml'
    | '/flows'
    | '/invest'
    | '/jobs'
    | '/reserves'
    | '/signals'
    | '/sources'
    | '/substack'
    | '/trade'
    | '/continents/$slug'
    | '/dispatch/$slug'
    | '/producers/$slug'
    | '/continents'
    | '/dispatch'
    | '/producers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ais'
    | '/briefing'
    | '/continents'
    | '/dispatch'
    | '/feed.xml'
    | '/flows'
    | '/invest'
    | '/jobs'
    | '/producers'
    | '/reserves'
    | '/signals'
    | '/sources'
    | '/substack'
    | '/trade'
    | '/continents/$slug'
    | '/dispatch/$slug'
    | '/producers/$slug'
    | '/continents/'
    | '/dispatch/'
    | '/producers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AisRoute: typeof AisRoute
  BriefingRoute: typeof BriefingRoute
  ContinentsRoute: typeof ContinentsRouteWithChildren
  DispatchRoute: typeof DispatchRouteWithChildren
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  FlowsRoute: typeof FlowsRoute
  InvestRoute: typeof InvestRoute
  JobsRoute: typeof JobsRoute
  ProducersRoute: typeof ProducersRouteWithChildren
  ReservesRoute: typeof ReservesRoute
  SignalsRoute: typeof SignalsRoute
  SourcesRoute: typeof SourcesRoute
  SubstackRoute: typeof SubstackRoute
  TradeRoute: typeof TradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ais': {
      id: '/ais'
      path: '/ais'
      fullPath: '/ais'
      preLoaderRoute: typeof AisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continents': {
      id: '/continents'
      path: '/continents'
      fullPath: '/continents'
      preLoaderRoute: typeof ContinentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producers': {
      id: '/producers'
      path: '/producers'
      fullPath: '/producers'
      preLoaderRoute: typeof ProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserves': {
      id: '/reserves'
      path: '/reserves'
      fullPath: '/reserves'
      preLoaderRoute: typeof ReservesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substack': {
      id: '/substack'
      path: '/substack'
      fullPath: '/substack'
      preLoaderRoute: typeof SubstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continents/': {
      id: '/continents/'
      path: '/'
      fullPath: '/continents/'
      preLoaderRoute: typeof ContinentsIndexRouteImport
      parentRoute: typeof ContinentsRoute
    }
    '/continents/$slug': {
      id: '/continents/$slug'
      path: '/$slug'
      fullPath: '/continents/$slug'
      preLoaderRoute: typeof ContinentsSlugRouteImport
      parentRoute: typeof ContinentsRoute
    }
    '/dispatch/': {
      id: '/dispatch/'
      path: '/'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof DispatchIndexRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/$slug': {
      id: '/dispatch/$slug'
      path: '/$slug'
      fullPath: '/dispatch/$slug'
      preLoaderRoute: typeof DispatchSlugRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/producers/': {
      id: '/producers/'
      path: '/'
      fullPath: '/producers/'
      preLoaderRoute: typeof ProducersIndexRouteImport
      parentRoute: typeof ProducersRoute
    }
    '/producers/$slug': {
      id: '/producers/$slug'
      path: '/$slug'
      fullPath: '/producers/$slug'
      preLoaderRoute: typeof ProducersSlugRouteImport
      parentRoute: typeof ProducersRoute
    }
  }
}

interface ContinentsRouteChildren {
  ContinentsSlugRoute: typeof ContinentsSlugRoute
  ContinentsIndexRoute: typeof ContinentsIndexRoute
}

const ContinentsRouteChildren: ContinentsRouteChildren = {
  ContinentsSlugRoute: ContinentsSlugRoute,
  ContinentsIndexRoute: ContinentsIndexRoute,
}

const ContinentsRouteWithChildren = ContinentsRoute._addFileChildren(
  ContinentsRouteChildren,
)

interface DispatchRouteChildren {
  DispatchSlugRoute: typeof DispatchSlugRoute
  DispatchIndexRoute: typeof DispatchIndexRoute
}

const DispatchRouteChildren: DispatchRouteChildren = {
  DispatchSlugRoute: DispatchSlugRoute,
  DispatchIndexRoute: DispatchIndexRoute,
}

const DispatchRouteWithChildren = DispatchRoute._addFileChildren(
  DispatchRouteChildren,
)

interface ProducersRouteChildren {
  ProducersSlugRoute: typeof ProducersSlugRoute
  ProducersIndexRoute: typeof ProducersIndexRoute
}

const ProducersRouteChildren: ProducersRouteChildren = {
  ProducersSlugRoute: ProducersSlugRoute,
  ProducersIndexRoute: ProducersIndexRoute,
}

const ProducersRouteWithChildren = ProducersRoute._addFileChildren(
  ProducersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AisRoute: AisRoute,
  BriefingRoute: BriefingRoute,
  ContinentsRoute: ContinentsRouteWithChildren,
  DispatchRoute: DispatchRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  FlowsRoute: FlowsRoute,
  InvestRoute: InvestRoute,
  JobsRoute: JobsRoute,
  ProducersRoute: ProducersRouteWithChildren,
  ReservesRoute: ReservesRoute,
  SignalsRoute: SignalsRoute,
  SourcesRoute: SourcesRoute,
  SubstackRoute: SubstackRoute,
  TradeRoute: TradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
